version: '3.8'

services:
  streamlit:
    image: chatapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - qdrant
    environment:
      - QDRANT_URL=http://qdrant:6333

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
